<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150803/1-150P3234016.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150803/1-150P3234016.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="875";
$z[1][4]['height']="519";
$z[2]=Array("img"," /uploads/allimg/150803/1-150P3234022.jpg ",240,386);
$z[2][4]['ddimg']="/uploads/allimg/150803/1-150P3234022.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1024";
$z[2][4]['height']="768";
$z[3]=Array("img"," /uploads/allimg/150803/1-150P3234024.jpg ",388,534);
$z[3][4]['ddimg']="/uploads/allimg/150803/1-150P3234024.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1024";
$z[3][4]['height']="683";
$z[4]=Array("img"," /uploads/allimg/150803/1-150P3234027.jpg ",536,681);
$z[4][4]['ddimg']="/uploads/allimg/150803/1-150P3234027.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="620";
$z[4][4]['height']="465";
$z[5]=Array("img"," /uploads/allimg/150803/1-150P3234030.jpg ",683,828);
$z[5][4]['ddimg']="/uploads/allimg/150803/1-150P3234030.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="674";
$z[5][4]['height']="390";

?>