<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150803/1-150P3234314.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150803/1-150P3234314.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="875";
$z[1][4]['height']="519";
$z[2]=Array("img"," /uploads/allimg/150803/1-150P3234316.jpg ",240,386);
$z[2][4]['ddimg']="/uploads/allimg/150803/1-150P3234316.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1000";
$z[2][4]['height']="662";
$z[3]=Array("img"," /uploads/allimg/150803/1-150P3234319.jpg ",388,533);
$z[3][4]['ddimg']="/uploads/allimg/150803/1-150P3234319.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="658";
$z[3][4]['height']="477";
$z[4]=Array("img"," /uploads/allimg/150803/1-150P3234322.jpg ",535,681);
$z[4][4]['ddimg']="/uploads/allimg/150803/1-150P3234322.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1024";
$z[4][4]['height']="768";
$z[5]=Array("img"," /uploads/allimg/150803/1-150P3234325.jpg ",683,829);
$z[5][4]['ddimg']="/uploads/allimg/150803/1-150P3234325.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="1024";
$z[5][4]['height']="653";

?>