<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150803/1-150P3230551.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150803/1-150P3230551.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="875";
$z[1][4]['height']="519";
$z[2]=Array("img"," /uploads/allimg/150803/1-150P3230554.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/150803/1-150P3230554.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="702";
$z[2][4]['height']="556";
$z[3]=Array("img"," /uploads/allimg/150803/1-150P3230556.jpg ",387,532);
$z[3][4]['ddimg']="/uploads/allimg/150803/1-150P3230556.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="640";
$z[3][4]['height']="427";
$z[4]=Array("img"," /uploads/allimg/150803/1-150P3230559.jpg ",534,679);
$z[4][4]['ddimg']="/uploads/allimg/150803/1-150P3230559.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="834";
$z[4][4]['height']="716";
$z[5]=Array("img"," /uploads/allimg/150803/1-150P3230602.jpg ",681,826);
$z[5][4]['ddimg']="/uploads/allimg/150803/1-150P3230602.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="700";
$z[5][4]['height']="502";

?>