<?php
$z[0]=Array("field","",399,418);
$z[0][4]['name']="title";
$z[1]=Array("global","",419,445);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1164,1199);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1356,1375);
$z[3][4]['name']="title";
$z[4]=Array("productimagelist","\r\n			<div class=\"item fl PicPath [field:global name=autoindex runphp='yes']@me=(@me==0)?'cur':'';[/field:global]\"><img src=\"[field:imgsrc/]\" width=\"180\" height=\"103\" /><span></span>\r\n              <div class=\"dg\"></div>\r\n              <div class=\"mask\">[field:alttext/]</div>\r\n            </div>\r\n			",1597,1944);
$z[5]=Array("productimagelist","\r\n		<div class=\"item\" style=\"[field:global name=autoindex runphp='yes']@me=(@me==0)?' display:block; ':' display:none; ';[/field:global]\"> <img src=\"[field:imgsrc/]\" width=\"875\" />\r\n        </div>\r\n        ",2085,2338);
$z[6]=Array("field","",2397,2415);
$z[6][4]['name']="body";
$z[7]=Array("include","",3396,3433);
$z[7][4]['filename']="footer.htm";

?>