<?php
$z[0]=Array("field","",399,418);
$z[0][4]['name']="title";
$z[1]=Array("global","",419,445);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1164,1199);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","\r\n<div class=\"cn\">[field:typename /]</div>\r\n      ",1305,1390);
$z[3][4]['typeid']="18";
$z[4]=Array("channel","\r\n	  <div class=\"item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></div>\r\n	   ",1467,1694);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[4][4]['currentstyle']="<div class='item'><a href='~typelink~' class='on'>~typename~</a></div>";
$z[5]=Array("field","",1854,1873);
$z[5][4]['name']="title";
$z[6]=Array("field","",1904,1922);
$z[6][4]['name']="body";
$z[7]=Array("include","",2037,2074);
$z[7][4]['filename']="footer.htm";

?>