
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:add itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:add>

<field:tell itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tell>

<field:emial itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:emial>

<field:liuyan itemname="留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:liuyan>
