<div class="item clearfix">
          <div class="img fl"><a href="[field:arcurl/]"><img src="[field:picname/]" width="148" /></a></div>
          <div class="rd fr">
		    <div class="rd_t clearfix">
              <div class="fl dd">
                <div class="day">[field:pubdate function="MyDate('d',@me)"/]</div>
                <div class="year">[field:pubdate function="MyDate('Y-m',@me)"/]</div>
              </div>
              <div class="fl hl">
                <div class="t2">[field:title/]</div>
              </div>
            </div>
		    <!-- .rd_t end -->
            <div class="brief"> [field:infos/]…</div>
            <div class="more"> <a href="[field:arcurl/]">查看全部内容 &gt;</a> </div>
          </div>
          <!-- .rd end -->
        </div>