<div class="item fl ">
                	<div class="img">
                    	<a href="[field:arcurl/]"><img src="[field:picname/]" /><img src="[field:picname/]" style="display:none;" /></a>
                        <div class="hover"><a href="[field:arcurl/]">[field:title/]</a></div>
                    </div>
                    <div class="name"><a href="[field:arcurl/]">[field:title/]</a></div>
                </div>