<?php
$z[0]=Array("global","",399,425);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n	  <div class=\"i fl\"><a href=\"[field:typeurl/]\" class=\"\">[field:typename/]</a></div>\r\n	  ",2026,2174);
$z[1][4]['row']="10";
$z[1][4]['type']="top";
$z[1][4]['col']="1";
$z[2]=Array("global","",2574,2600);
$z[2][4]['name']="cfg_banquan";
$z[3]=Array("global","",2770,2794);
$z[3][4]['name']="cfg_beian";

?>