<?php
$z[0]=Array("field","",468,487);
$z[0][4]['name']="title";
$z[1]=Array("global","",488,514);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1222,1257);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","\r\n<div class=\"cn\">[field:typename /]</div>\r\n      ",1365,1449);
$z[3][4]['typeid']="7";
$z[4]=Array("channel","\r\n	  <div class=\"item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></div>\r\n	   ",1544,1771);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[4][4]['currentstyle']="<div class='item'><a href='~typelink~' class='on'>~typename~</a></div>";
$z[5]=Array("list","\r\n			<div class=\"item fl PicPath \"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"  alt=\"[field:title/]\" target=\"_blank\"><img src=\"[field:picname/]\" width=\"185\" height=\"121\"></a><span></span></div>\r\n			",2224,2464);
$z[5][4]['pagesize']="12";
$z[6]=Array("pagelist","",2552,2601);
$z[6][4]['istitem']="pre,next,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",3171,3208);
$z[7][4]['filename']="footer.htm";

?>