<?php
$z[0]=Array("field","",399,418);
$z[0][4]['name']="title";
$z[1]=Array("global","",419,445);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1164,1199);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","\r\n<div class=\"cn\">[field:typename /]</div>\r\n      ",1307,1392);
$z[3][4]['typeid']="18";
$z[4]=Array("channel","\r\n	  <div class=\"item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></div>\r\n	   ",1478,1705);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[4][4]['currentstyle']="<div class='item'><a href='~typelink~' class='on'>~typename~</a></div>";
$z[5]=Array("list","\r\n		<div class=\"item clearfix\">\r\n          <div class=\"img fl\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"148\" /></a></div>\r\n          <div class=\"rd fr\">\r\n		    <div class=\"rd_t clearfix\">\r\n              <div class=\"fl dd\">\r\n                <div class=\"day\">[field:pubdate function=\"MyDate('d',@me)\"/]</div>\r\n                <div class=\"year\">[field:pubdate function=\"MyDate('Y-m',@me)\"/]</div>\r\n              </div>\r\n              <div class=\"fl hl\">\r\n                <div class=\"t2\">[field:title/]</div>\r\n              </div>\r\n            </div>\r\n		    <!-- .rd_t end -->\r\n            <div class=\"brief\"> [field:infos/]…</div>\r\n            <div class=\"more\"> <a href=\"[field:arcurl/]\">查看全部内容 &gt;</a> </div>\r\n          </div>\r\n          <!-- .rd end -->\r\n        </div>\r\n		",1859,2717);
$z[5][4]['pagesize']="4";
$z[5][4]['infolen']="150";
$z[6]=Array("pagelist","",2856,2905);
$z[6][4]['istitem']="pre,next,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",3227,3264);
$z[7][4]['filename']="footer.htm";

?>