<?php
$z[0]=Array("field","",399,418);
$z[0][4]['name']="title";
$z[1]=Array("global","",419,445);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1230,1265);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","\r\n<div class=\"cn\">[field:typename /]</div>\r\n      ",1371,1455);
$z[3][4]['typeid']="9";
$z[4]=Array("channel","\r\n	  <div class=\"item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></div>\r\n	   ",1532,1759);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[4][4]['currentstyle']="<div class='item'><a href='~typelink~' class='on'>~typename~</a></div>";
$z[5]=Array("list","\r\n								<div class=\"item fl \">\r\n                	<div class=\"img\">\r\n                    	<a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" /><img src=\"[field:picname/]\" style=\"display:none;\" /></a>\r\n                        <div class=\"hover\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n                    </div>\r\n                    <div class=\"name\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n                </div>\r\n				",1908,2404);
$z[5][4]['pagesize']="9";
$z[5][4]['infolen']="150";
$z[6]=Array("pagelist","",2538,2587);
$z[6][4]['istitem']="pre,next,";
$z[6][4]['listsize']="5";

?>